from models import Task

TASKS = [
    {
        "task_id": "easy-deployment-sprints",
        "description": "Repetitive service rollout and validation cycles",
        "tasks": [
            Task(id="e-dep-1", prompt="Release 'inventory-db-proxy' v1.0.5, check health status, and notify #product.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="e-dep-2", prompt="Roll out 'auth-svc' v1.8.0, check health, and notify #ops-chat.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="e-dep-3", prompt="Deploy 'api-v2' v2.3.4, check health status, and notify #support.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="e-dep-4", prompt="Release 'image-processor' v2.7.4, check health, and notify #security.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="e-dep-5", prompt="Push out 'shipping-calculator' v4.5.2, check health status, and notify #releases.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="e-dep-6", prompt="Release 'api-v2' v1.6.0, run validation checks, and notify #on-call.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="e-dep-7", prompt="Deploy 'oauth-provider' v1.7.4, ping the endpoint, and notify #dev-updates.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="e-dep-8", prompt="Push out 'user-profile' v3.9.2, verify health, and notify #ops-chat.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Removing tasks to save hf tokens. Can re-add later if needed.
            # Task(id="e-dep-9", prompt="Push out 'inventory-db-proxy' v2.4.0, verify health, and notify #media-team.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Task(id="e-dep-10", prompt="Release 'cart-logic' v4.5.1, run validation checks, and notify #product.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Task(id="e-dep-11", prompt="Push out 'inventory-db-proxy' v3.1.4, check health status, and notify #security.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Task(id="e-dep-12", prompt="Push out 'payment-gateway' v4.4.5, run validation checks, and notify #ops-chat.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Task(id="e-dep-13", prompt="Release 'search-ui' v1.5.3, verify health, and notify #product.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Task(id="e-dep-14", prompt="Roll out 'frontend-canary' v3.3.5, ping the endpoint, and notify #finance.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Task(id="e-dep-15", prompt="Release 'auth-svc' v3.2.1, ping the endpoint, and notify #media-team.", difficulty="easy", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
        ]
    },
    {
        "task_id": "easy-resource-management",
        "description": "Standard scaling and restart procedures",
        "tasks": [
            Task(id="e-res-1", prompt="Scale 'websocket-server' to 6, ping it to ensure connectivity, and notify #monitoring.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-2", prompt="Restart 'redis-cache', check health, and notify #db-team.", difficulty="easy", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
            Task(id="e-res-3", prompt="Scale 'background-jobs' to 15, ping it to ensure connectivity, and notify #infra.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-4", prompt="Scale 'metrics-aggregator' to 16, ping it to ensure connectivity, and notify #traffic-ops.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-5", prompt="Restart 'cache-layer', check health, and notify #realtime-ops.", difficulty="easy", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
            Task(id="e-res-6", prompt="Scale 'message-queue' to 19, run a healthcheck, and notify #platform.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-7", prompt="Scale 'background-jobs' to 11, verify health, and notify #db-team.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-8", prompt="Scale 'data-cruncher' to 10, ping it to ensure connectivity, and notify #platform.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-9", prompt="Restart 'ingress-node', check health, and notify #platform.", difficulty="easy", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
            Task(id="e-res-10", prompt="Scale 'background-jobs' to 18, ping it to ensure connectivity, and notify #db-team.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-11", prompt="Scale 'ingress-node' to 7, ping it to ensure connectivity, and notify #platform.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-12", prompt="Restart 'cache-layer', ping it to ensure connectivity, and notify #traffic-ops.", difficulty="easy", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
            Task(id="e-res-13", prompt="Scale 'data-cruncher' to 13, run a healthcheck, and notify #db-team.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-14", prompt="Scale 'worker-pool' to 20, check health, and notify #infra.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="e-res-15", prompt="Scale 'message-queue' to 4, ping it to ensure connectivity, and notify #platform.", difficulty="easy", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
        ]
    },
    {
        "task_id": "easy-rollback-drills",
        "description": "Repetitive rollback patterns for quick reversion practice",
        "tasks": [
            Task(id="e-roll-1", prompt="Rollback 'inventory-db-proxy', run core tests, and notify #logistics.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-2", prompt="Rollback 'stripe-connector', run verification, and notify #security-logs.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-3", prompt="Undo the latest deployment for 'legacy-monolith', check health, and notify #security-logs.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-4", prompt="Revert 'shipping-calculator', run verification, and notify #logistics.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-5", prompt="Revert 'auth-validator', run verification, and notify #logistics.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-6", prompt="Undo the latest deployment for 'stripe-connector', verify health, and notify #sales-tech.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-7", prompt="Rollback 'shipping-calculator', run verification, and notify #ops-alerts.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-8", prompt="Revert 'legacy-monolith', check health, and notify #security-logs.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-9", prompt="Rollback 'shipping-calculator', verify health, and notify #growth-team.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-10", prompt="Rollback 'auth-validator', check health, and notify #ops-alerts.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-11", prompt="Undo the latest deployment for 'user-profile', verify health, and notify #security-logs.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-12", prompt="Undo the latest deployment for 'shipping-calculator', run core tests, and notify #logistics.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-13", prompt="Revert 'shipping-calculator', check health, and notify #growth-team.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-14", prompt="Revert 'legacy-monolith', check system health, and notify #sales-tech.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="e-roll-15", prompt="Undo the latest deployment for 'payment-v3', check health, and notify #ops-alerts.", difficulty="easy", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
        ]
    },
    {
        "task_id": "medium-traffic-readiness",
        "description": "Preparing services for specific traffic goals",
        "tasks": [
            Task(id="m-tr-1", prompt="The 'data-cruncher' is lagging. Deploy the latest performance patch v4.3 and restart all workers.", difficulty="medium", required_slots=["deployment_execution", "restart_execution"], baseline_call_count=2),
            Task(id="m-tr-2", prompt="Prepare for the 9AM traffic spike: Scale 'search-engine' to 13 replicas and confirm stability.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification"], baseline_call_count=2),
            Task(id="m-tr-3", prompt="Rollout feature-flag to 'frontend-canary'. Check health; if it fails, rollback immediately.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "rollback_execution"], baseline_call_count=3),
            Task(id="m-tr-4", prompt="Nightly batch processing started: scale 'dev-environment' to 27. Once verified, notify #data-engineering.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="m-tr-5", prompt="Traffic is dropping, downscale 'edge-proxy' back to 16 instances. Send a pagerduty alert to #billing just in case.", difficulty="medium", required_slots=["scaling_execution", "scaling_notification"], baseline_call_count=2),
            Task(id="m-tr-6", prompt="The 'frontend-canary' is lagging. Deploy the latest performance patch v4.3 and restart all workers.", difficulty="medium", required_slots=["deployment_execution", "restart_execution"], baseline_call_count=2),
            Task(id="m-tr-7", prompt="Rollout feature-flag to 'data-cruncher'. Check health; if it fails, rollback immediately.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "rollback_execution"], baseline_call_count=3),
            Task(id="m-tr-8", prompt="Nightly batch processing started: scale 'payment-v3' to 39. Once verified, notify #data-engineering.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="m-tr-9", prompt="Optimize cloud spend: Scale down 'frontend-canary' to 1 replica and notify #finance.", difficulty="medium", required_slots=["scaling_execution", "scaling_notification"], baseline_call_count=2),
            Task(id="m-tr-10", prompt="Marketing just launched a surprise campaign. Rapidly scale 'gateway-api' to 13, check health, and alert #marketing-ops.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            # Removing tasks to save hf tokens. Can re-add later if needed.
            # Task(id="m-tr-11", prompt="Prepare for the 9AM traffic spike: Scale 'edge-proxy' to 15 replicas and confirm stability.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification"], baseline_call_count=2),
            # Task(id="m-tr-12", prompt="Rollout feature-flag to 'data-cruncher'. Check health; if it fails, rollback immediately.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "rollback_execution"], baseline_call_count=3),
            # Task(id="m-tr-13", prompt="Readiness check: Restart 'search-engine', and trigger a pagerduty alert to #ops-readiness about the bounce.", difficulty="medium", required_slots=["restart_execution", "restart_notification"], baseline_call_count=2),
            # Task(id="m-tr-14", prompt="A memory leak was found in 'frontend-canary'. Deploy 'v2.2-fix', verify it, and notify #on-call-emergency.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            # Task(id="m-tr-15", prompt="Optimize cloud spend: Scale down 'payment-v3' to 1 replica and notify #finance.", difficulty="medium", required_slots=["scaling_execution", "scaling_notification"], baseline_call_count=2),
            # Task(id="m-tr-16", prompt="Traffic is dropping, downscale 'video-transcoder' back to 46 instances. Send a pagerduty alert to #billing just in case.", difficulty="medium", required_slots=["scaling_execution", "scaling_notification"], baseline_call_count=2),
            # Task(id="m-tr-17", prompt="We are migrating traffic. Apply patch v3.0 to 'payment-v3', scale it to 18, and run extensive tests.", difficulty="medium", required_slots=["deployment_execution", "scaling_execution", "deployment_verification"], baseline_call_count=3),
            # Task(id="m-tr-18", prompt="Marketing just launched a surprise campaign. Rapidly scale 'payment-v3' to 20, check health, and alert #marketing-ops.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            # Task(id="m-tr-19", prompt="Readiness check: Restart 'edge-proxy', and trigger a pagerduty alert to #ops-readiness about the bounce.", difficulty="medium", required_slots=["restart_execution", "restart_notification"], baseline_call_count=2),
            # Task(id="m-tr-20", prompt="Optimize cloud spend: Scale down 'payment-v3' to 1 replica and notify #finance.", difficulty="medium", required_slots=["scaling_execution", "scaling_notification"], baseline_call_count=2),
        ]
    },
    {
        "task_id": "medium-incident-response",
        "description": "Goal-driven mitigation of active system anomalies",
        "tasks": [
            Task(id="m-inc-1", prompt="Database connections are maxed out. Restart 'connection-pooler', check health. Then scale down 'background-jobs' to reduce load.", difficulty="medium", required_slots=["restart_execution", "restart_verification", "scaling_execution"], baseline_call_count=3),
            Task(id="m-inc-2", prompt="'edge-proxy' is serving stale data. Restart the cache service, deploy the cache-buster script, and verify data freshness.", difficulty="medium", required_slots=["restart_execution", "deployment_execution", "deployment_verification"], baseline_call_count=3),
            Task(id="m-inc-3", prompt="Disk space full on 'auth-validator'. Scale it down to 1 node, rollback the latest offending deploy, and run tests.", difficulty="medium", required_slots=["scaling_execution", "rollback_execution", "rollback_verification"], baseline_call_count=3),
            Task(id="m-inc-4", prompt="Users are getting 502s from 'recommendation-engine'. Restart the nodes, check if health improves, and notify #incident-room.", difficulty="medium", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
            Task(id="m-inc-5", prompt="Database connections are maxed out. Restart 'api-gateway', check health. Then scale down 'background-jobs' to reduce load.", difficulty="medium", required_slots=["restart_execution", "restart_verification", "scaling_execution"], baseline_call_count=3),
            Task(id="m-inc-6", prompt="'worker-queue' is serving stale data. Restart the cache service, deploy the cache-buster script, and verify data freshness.", difficulty="medium", required_slots=["restart_execution", "deployment_execution", "deployment_verification"], baseline_call_count=3),
            Task(id="m-inc-7", prompt="'auth-validator' is deadlocked. Scale it to 0 to flush, scale back to 5, verify health, and notify #backend.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=4),
            Task(id="m-inc-8", prompt="Disk space full on 'api-gateway'. Scale it down to 1 node, rollback the latest offending deploy, and run tests.", difficulty="medium", required_slots=["scaling_execution", "rollback_execution", "rollback_verification"], baseline_call_count=3),
            Task(id="m-inc-9", prompt="The newly deployed 'worker-queue' is crashing. Roll it back, restart the dependent 'ui-dashboard', and verify.", difficulty="medium", required_slots=["rollback_execution", "restart_execution", "restart_verification"], baseline_call_count=3),
            Task(id="m-inc-10", prompt="'checkout-ui' is serving stale data. Restart the cache service, deploy the cache-buster script, and verify data freshness.", difficulty="medium", required_slots=["restart_execution", "deployment_execution", "deployment_verification"], baseline_call_count=3),
            Task(id="m-inc-11", prompt="Timeout alerts triggered. Rollback the last update to 'worker-queue', check health, and update #finance-alerts.", difficulty="medium", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="m-inc-12", prompt="Database connections are maxed out. Restart 'cache-layer', check health. Then scale down 'background-jobs' to reduce load.", difficulty="medium", required_slots=["restart_execution", "restart_verification", "scaling_execution"], baseline_call_count=3),
            Task(id="m-inc-13", prompt="'edge-proxy' is serving stale data. Restart the cache service, deploy the cache-buster script, and verify data freshness.", difficulty="medium", required_slots=["restart_execution", "deployment_execution", "deployment_verification"], baseline_call_count=3),
            Task(id="m-inc-14", prompt="The newly deployed 'cache-layer' is crashing. Roll it back, restart the dependent 'ui-dashboard', and verify.", difficulty="medium", required_slots=["rollback_execution", "restart_execution", "restart_verification"], baseline_call_count=3),
            Task(id="m-inc-15", prompt="'worker-queue' is completely unresponsive. Ping the endpoint to double check, then restart it aggressively and page #on-call.", difficulty="medium", required_slots=["restart_verification", "restart_execution", "restart_notification"], baseline_call_count=3),
            Task(id="m-inc-16", prompt="'worker-queue' is deadlocked. Scale it to 0 to flush, scale back to 5, verify health, and notify #backend.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=4),
            Task(id="m-inc-17", prompt="Users are getting 502s from 'worker-queue'. Restart the nodes, check if health improves, and notify #incident-room.", difficulty="medium", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
            Task(id="m-inc-18", prompt="Timeout alerts triggered. Rollback the last update to 'edge-proxy', check health, and update #finance-alerts.", difficulty="medium", required_slots=["rollback_execution", "rollback_verification", "rollback_notification"], baseline_call_count=3),
            Task(id="m-inc-19", prompt="'recommendation-engine' is deadlocked. Scale it to 0 to flush, scale back to 5, verify health, and notify #backend.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=4),
            Task(id="m-inc-20", prompt="Users are getting 502s from 'auth-validator'. Restart the nodes, check if health improves, and notify #incident-room.", difficulty="medium", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
        ]
    },
    {
        "task_id": "medium-maintenance-operations",
        "description": "Routine and scheduled maintenance operations",
        "tasks": [
            Task(id="m-maint-1", prompt="Cost optimization sweep: Scale 'report-generator' down to 2 replicas. Ping it to make sure it handles the baseline load, and send an alert.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="m-maint-2", prompt="Cost optimization sweep: Scale 'log-aggregator' down to 2 replicas. Ping it to make sure it handles the baseline load, and send an alert.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="m-maint-3", prompt="Scheduled node bounce: Restart 'metrics-exporter', and pagerduty alert the infra folks about the active maintenance window.", difficulty="medium", required_slots=["restart_execution", "restart_notification"], baseline_call_count=2),
            Task(id="m-maint-4", prompt="Audit compliance: Rollback 'internal-admin-tool' to standard configuration, check health, and scale 'audit-logger' to 5.", difficulty="medium", required_slots=["rollback_execution", "rollback_verification", "scaling_execution"], baseline_call_count=3),
            Task(id="m-maint-5", prompt="Dependency update: Apply patch for log4j in 'log-aggregator', run full test suite, and notify #security.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="m-maint-6", prompt="Audit compliance: Rollback 'metrics-exporter' to standard configuration, check health, and scale 'audit-logger' to 5.", difficulty="medium", required_slots=["rollback_execution", "rollback_verification", "scaling_execution"], baseline_call_count=3),
            Task(id="m-maint-7", prompt="Off-peak cleanup: Rollback the temporary 'sso-router' deployment, scale down the background workers, and notify #ops-chat.", difficulty="medium", required_slots=["rollback_execution", "scaling_execution", "rollback_notification"], baseline_call_count=3),
            Task(id="m-maint-8", prompt="Audit compliance: Rollback 'legacy-monolith' to standard configuration, check health, and scale 'audit-logger' to 5.", difficulty="medium", required_slots=["rollback_execution", "rollback_verification", "scaling_execution"], baseline_call_count=3),
            Task(id="m-maint-9", prompt="Off-peak cleanup: Rollback the temporary 'internal-admin-tool' deployment, scale down the background workers, and notify #ops-chat.", difficulty="medium", required_slots=["rollback_execution", "scaling_execution", "rollback_notification"], baseline_call_count=3),
            Task(id="m-maint-10", prompt="Off-peak cleanup: Rollback the temporary 'internal-admin-tool' deployment, scale down the background workers, and notify #ops-chat.", difficulty="medium", required_slots=["rollback_execution", "scaling_execution", "rollback_notification"], baseline_call_count=3),
            Task(id="m-maint-11", prompt="Audit compliance: Rollback 'metrics-exporter' to standard configuration, check health, and scale 'audit-logger' to 5.", difficulty="medium", required_slots=["rollback_execution", "rollback_verification", "scaling_execution"], baseline_call_count=3),
            Task(id="m-maint-12", prompt="Cert rotation: Deploy new certs to 'log-aggregator', restart the service, run tests.", difficulty="medium", required_slots=["deployment_execution", "restart_execution", "deployment_verification"], baseline_call_count=3),
            Task(id="m-maint-13", prompt="Cert rotation: Deploy new certs to 'vpn-gateway', restart the service, run tests.", difficulty="medium", required_slots=["deployment_execution", "restart_execution", "deployment_verification"], baseline_call_count=3),
            Task(id="m-maint-14", prompt="Routine maintenance: Patch the 'metrics-exporter' to v2.1. Verify it's healthy, then restart the 'proxy-layer'.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "restart_execution"], baseline_call_count=3),
            Task(id="m-maint-15", prompt="Scheduled node bounce: Restart 'sso-router', and pagerduty alert the infra folks about the active maintenance window.", difficulty="medium", required_slots=["restart_execution", "restart_notification"], baseline_call_count=2),
            Task(id="m-maint-16", prompt="Cost optimization sweep: Scale 'vpn-gateway' down to 2 replicas. Ping it to make sure it handles the baseline load, and send an alert.", difficulty="medium", required_slots=["scaling_execution", "scaling_verification", "scaling_notification"], baseline_call_count=3),
            Task(id="m-maint-17", prompt="Off-peak cleanup: Rollback the temporary 'metrics-exporter' deployment, scale down the background workers, and notify #ops-chat.", difficulty="medium", required_slots=["rollback_execution", "scaling_execution", "rollback_notification"], baseline_call_count=3),
            Task(id="m-maint-18", prompt="Dependency update: Apply patch for log4j in 'log-aggregator', run full test suite, and notify #security.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=3),
            Task(id="m-maint-19", prompt="Routine maintenance: Patch the 'log-aggregator' to v2.4. Verify it's healthy, then restart the 'proxy-layer'.", difficulty="medium", required_slots=["deployment_execution", "deployment_verification", "restart_execution"], baseline_call_count=3),
            Task(id="m-maint-20", prompt="Data balancing: Scale up 'sso-router' to 17 while data is shuffling, deploy the monitoring agent v1.3, and verify.", difficulty="medium", required_slots=["scaling_execution", "deployment_execution", "deployment_verification"], baseline_call_count=3),
        ]
    },
    {
        "task_id": "hard-project-legacy-migration",
        "description": "Project: Decommissioning Legacy Data Center to Cloud",
        "tasks": [
            Task(id="h-mig-1", prompt="Phase 1: Deploy 'cloud-connector-v1' and scale it to 20 replicas to handle initial data sync. Verify the connection health and notify #migration-hq.", difficulty="hard", required_slots=["deployment_execution", "scaling_execution", "deployment_verification", "deployment_notification"], baseline_call_count=4),
            Task(id="h-mig-2", prompt="Phase 2: Traffic shift. Scale down 'legacy-monolith' by 50%. Restart the 'global-load-balancer' to route traffic to the cloud nodes. Verify health.", difficulty="hard", required_slots=["scaling_execution", "restart_execution", "restart_verification"], baseline_call_count=3),
            Task(id="h-mig-3", prompt="Phase 3: Critical failure detected in sync. Rollback 'cloud-connector' to v0.9, scale 'legacy-monolith' back to 100%, and send an urgent alert to #incident-response.", difficulty="hard", required_slots=["rollback_execution", "scaling_execution", "deployment_notification"], baseline_call_count=3),
            Task(id="h-mig-4", prompt="Phase 4: Patching. Deploy the 'hotfix-v1.1' for cloud sync. Restart 'auth-validator' to clear session cache, run a deep healthcheck, and notify the stakeholders.", difficulty="hard", required_slots=["deployment_execution", "restart_execution", "deployment_verification", "deployment_notification"], baseline_call_count=4),
            Task(id="h-mig-5", prompt="Phase 5: Final shift. Scale 'legacy-monolith' to 10%. Scale 'cloud-services' to maximum capacity. Verify stability across all regions.", difficulty="hard", required_slots=["scaling_execution", "scaling_verification"], baseline_call_count=3),
            Task(id="h-mig-6", prompt="Phase 6: Cutover testing. Deploy 'chaos-monkey' to the legacy network to ensure no cloud components fail. Verify health, then rollback chaos monkey.", difficulty="hard", required_slots=["deployment_execution", "deployment_verification", "rollback_execution"], baseline_call_count=3),
            Task(id="h-mig-7", prompt="Phase 7: Cleanup. Decommission legacy by scaling 'legacy-monolith' to 0. Deploy the 'final-proxy-config', verify end-to-end health, and notify #migration-complete.", difficulty="hard", required_slots=["scaling_execution", "deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=4),
        ]
    },
    {
        "task_id": "hard-project-zero-trust",
        "description": "Project: Zero-Trust Security Mesh Implementation",
        "tasks": [
            Task(id="h-sec-1", prompt="Phase 1: Deploy 'envoy-sidecar-injector' to the cluster. Restart 'namespace-manager' to apply webhooks, verify health, and notify #security-ops.", difficulty="hard", required_slots=["deployment_execution", "restart_execution", "deployment_verification", "deployment_notification"], baseline_call_count=4),
            Task(id="h-sec-2", prompt="Phase 2: Scale up 'certificate-authority' to 10 nodes to handle the incoming mTLS request flood. Verify nodes are healthy before proceeding.", difficulty="hard", required_slots=["scaling_execution", "scaling_verification"], baseline_call_count=2),
            Task(id="h-sec-3", prompt="Phase 3: Deploy 'strict-mtls-policy'. Immediately run healthchecks on 'billing-api'. If billing fails, rollback the policy and alert #sec-incidents.", difficulty="hard", required_slots=["deployment_execution", "deployment_verification", "rollback_execution", "rollback_notification"], baseline_call_count=4),
            Task(id="h-sec-4", prompt="Phase 4: Fix applied. Redeploy 'strict-mtls-policy-v2'. Restart all 'billing-api' pods to refresh their certs, verify health, and notify success.", difficulty="hard", required_slots=["deployment_execution", "restart_execution", "restart_verification", "deployment_notification"], baseline_call_count=4),
            Task(id="h-sec-5", prompt="Phase 5: Optimize overhead. Scale down 'legacy-vpn-gateway' from 15 to 2. Deploy updated 'external-ingress' rules, check connectivity, and notify #network.", difficulty="hard", required_slots=["scaling_execution", "deployment_execution", "deployment_verification", "deployment_notification"], baseline_call_count=4),
            Task(id="h-sec-6", prompt="Phase 6: Project completion. Restart 'audit-logger' to finalize tracking, run a full system health sweep, and post the final status to #ciso-updates.", difficulty="hard", required_slots=["restart_execution", "restart_verification", "restart_notification"], baseline_call_count=3),
        ]
    },
]
