from models import Task

TASKS = [
    {
        "task_id": "easy-deployment-sprints",
        "description": "Repetitive service rollout and validation cycles",
        "tasks": [
            Task(
                id="e2-dep-1",
                prompt="Ship 'billing-edge' v2.6.1, run health checks on /ready and /checkout, and notify #release-train.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-2",
                prompt="Canary release 'catalog-search' v5.1.0. Verify p95 latency; if canary is unstable, restart canary pods before notifying #ops-bridge.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "restart_execution", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-dep-3",
                prompt="Roll out 'session-router' v4.8.0, verify token refresh flow, and post an update in #identity-ops.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-4",
                prompt="Deploy 'invoice-worker' v3.0.9, run smoke tests, and notify #finance-platform.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-5",
                prompt="Promote 'media-gateway' v2.1.3, check stream and auth endpoints, then notify #media-ops.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-6",
                prompt="Deploy 'cart-pricing' v7.2.5 and run quick validation; if health flaps, restart the service and notify #commerce-alerts.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "restart_execution", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-dep-7",
                prompt="Release 'profile-aggregator' v1.3.7, verify dependency reachability, and notify #customer-experience.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-8",
                prompt="Deploy 'orders-api' v6.4.2, verify health from two zones, and notify #ops-chat.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-9",
                prompt="Promote 'inventory-sync' v2.5.8, validate sync endpoint health, and notify #supply-chain-ops.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-10",
                prompt="Deploy 'checkout-api' v8.0.1, run smoke validation, and notify #commerce-alerts.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-11",
                prompt="Release 'email-dispatcher' v3.4.6, verify queue consumption health, and notify #notifications-team.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-12",
                prompt="Deploy 'returns-service' v1.9.2, verify refund path health, and notify #support-ops.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-13",
                prompt="Canary deploy 'search-ranking' v4.0.0, verify relevance endpoint, restart canary if unstable, and notify #search-ops.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "restart_execution", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-dep-14",
                prompt="Roll out 'profile-cache' v2.2.4, run readiness checks, and notify #identity-ops.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-dep-15",
                prompt="Deploy 'shipping-rates' v5.6.3, verify pricing endpoint from two zones, and notify #logistics.",
                difficulty="easy",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
        ]
    },
    {
        "task_id": "easy-resource-management",
        "description": "Standard scaling and restart procedures",
        "tasks": [
            Task(
                id="e2-res-1",
                prompt="Scale 'realtime-fanout' to 12 replicas, verify request success rate, and notify #traffic-watch.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-2",
                prompt="Restart 'redis-cache', verify failover status, and notify #db-team.",
                difficulty="easy",
                required_slots=["restart_execution", "restart_verification", "restart_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-3",
                prompt="Scale 'worker-pool' to 24, run a healthcheck, and notify #infra.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-4",
                prompt="Restart 'api-throttle' and then scale 'edge-proxy' to 9. Verify stability after scale and notify #traffic-ops.",
                difficulty="easy",
                required_slots=["restart_execution", "scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-res-5",
                prompt="Scale 'webhook-gateway' to 14, confirm connectivity, and notify #platform.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-6",
                prompt="Restart 'ingestion-router', verify it recovered cleanly, and notify #data-ops.",
                difficulty="easy",
                required_slots=["restart_execution", "restart_verification", "restart_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-7",
                prompt="Scale 'search-indexer' to 11; if indexing stalls, restart it once and notify #search-ops.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "restart_execution", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-res-8",
                prompt="Scale 'notification-bus' to 16, verify delivery pipeline health, and notify #realtime-ops.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-9",
                prompt="Restart 'rate-limiter', verify traffic admission health, and notify #platform.",
                difficulty="easy",
                required_slots=["restart_execution", "restart_verification", "restart_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-10",
                prompt="Scale 'api-gateway' to 15, validate upstream connectivity, and notify #traffic-watch.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-11",
                prompt="Scale 'billing-workers' to 12, run health checks, and notify #finance-platform.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-12",
                prompt="Restart 'session-store', verify failover state, and notify #identity-ops.",
                difficulty="easy",
                required_slots=["restart_execution", "restart_verification", "restart_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-13",
                prompt="Scale 'event-processor' to 18, verify backlog drain rate, and notify #data-ops.",
                difficulty="easy",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-res-14",
                prompt="Scale 'checkout-cache' to 9 and restart it once to pick new config; verify healthy state and notify #commerce-alerts.",
                difficulty="easy",
                required_slots=["scaling_execution", "restart_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-res-15",
                prompt="Restart 'webhook-delivery', verify callback success, and notify #integrations.",
                difficulty="easy",
                required_slots=["restart_execution", "restart_verification", "restart_notification"],
                baseline_call_count=3,
            ),
        ]
    },
    {
        "task_id": "easy-rollback-drills",
        "description": "Repetitive rollback patterns for quick reversion practice",
        "tasks": [
            Task(
                id="e2-roll-1",
                prompt="Rollback 'checkout-api' to the previous stable build, run smoke verification, and notify #incident-room.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-2",
                prompt="Revert 'promo-engine', verify discount flow health, and notify #growth-team.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-3",
                prompt="Undo the latest deploy for 'auth-svc', run verification, and notify #security-logs.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-4",
                prompt="Rollback 'recommendations-api', restart the dependent cache layer, then notify #incident-room.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "restart_execution", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-roll-5",
                prompt="Revert 'billing-proxy', verify payment health checks, and notify #finance-alerts.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-6",
                prompt="Rollback 'image-transformer', run core tests, and notify #media-ops.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-7",
                prompt="Undo release for 'order-router'; verify recovery, restart if still unhealthy, and notify #ops-alerts.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "restart_execution", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-roll-8",
                prompt="Rollback 'search-ui', verify endpoint health, and notify #product.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-9",
                prompt="Rollback 'invoice-worker', verify retry queue behavior, and notify #finance-platform.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-10",
                prompt="Revert 'inventory-sync' to the last stable build, check health, and notify #supply-chain-ops.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-11",
                prompt="Undo latest deployment for 'session-router', verify token refresh flow, and notify #identity-ops.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-12",
                prompt="Rollback 'orders-api', restart dependent cache if needed, verify recovery, and notify #ops-chat.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "restart_execution", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="e2-roll-13",
                prompt="Revert 'returns-service', run smoke tests, and notify #support-ops.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-14",
                prompt="Rollback 'email-dispatcher', verify delivery queue health, and notify #notifications-team.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="e2-roll-15",
                prompt="Undo release for 'billing-edge', validate payment path, and notify #finance-alerts.",
                difficulty="easy",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
        ]
    },
    {
        "task_id": "medium-traffic-readiness",
        "description": "Preparing services for specific traffic goals",
        "tasks": [
            Task(
                id="m2-tr-1",
                prompt="Pre-launch drill: deploy 'gateway-api' v3.2.1, scale it to 18 replicas, verify p95 and error rate, then notify #marketing-ops.",
                difficulty="medium",
                required_slots=["deployment_execution", "scaling_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-2",
                prompt="Morning spike rehearsal: scale 'search-engine' to 22, verify stability, and if queue depth stays high restart 'query-coordinator' before notifying #traffic-war-room.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "restart_execution", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-3",
                prompt="Roll out a flag update to 'checkout-ui', validate health, and if conversion checks fail rollback immediately and alert #revenue-incident.",
                difficulty="medium",
                required_slots=["deployment_execution", "deployment_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-4",
                prompt="Patch 'video-transcoder' to v5.0.2, restart worker pool, verify output pipeline health, and notify #media-sre.",
                difficulty="medium",
                required_slots=["deployment_execution", "restart_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-5",
                prompt="Campaign readiness: scale 'edge-proxy' to 30, deploy rate-limit profile v2, verify traffic behavior, and notify #platform-ops.",
                difficulty="medium",
                required_slots=["scaling_execution", "deployment_execution", "deployment_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-6",
                prompt="Migration window: deploy 'cache-router' v1.1.4, scale to 10, verify cross-region hit ratio, and rollback if miss-rate spikes; alert #on-call-emergency.",
                difficulty="medium",
                required_slots=["deployment_execution", "scaling_execution", "deployment_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="m2-tr-7",
                prompt="Cost-control check: scale 'background-jobs' down to 6, verify SLA is still met, and notify #finance-alerts.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-tr-8",
                prompt="Readiness bounce: restart 'search-engine', deploy index patch v2.4, verify warmup success, and notify #search-ops.",
                difficulty="medium",
                required_slots=["restart_execution", "deployment_execution", "deployment_verification", "restart_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-9",
                prompt="Evening surge prep: scale 'checkout-api' to 20, verify cart completion latency, and notify #commerce-alerts.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-tr-10",
                prompt="Before ad launch, deploy 'inventory-sync' v3.0.1, verify stock sync health, and notify #supply-chain-ops.",
                difficulty="medium",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-tr-11",
                prompt="Traffic rebalance window: restart 'api-gateway', scale it to 16, verify route stability, and notify #traffic-war-room.",
                difficulty="medium",
                required_slots=["restart_execution", "scaling_execution", "scaling_verification", "restart_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-12",
                prompt="Deploy cache tuning patch to 'edge-proxy', verify hit ratio recovery, rollback if error rate rises, and alert #on-call-emergency.",
                difficulty="medium",
                required_slots=["deployment_execution", "deployment_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-13",
                prompt="Readiness rehearsal: scale 'notification-bus' to 18, restart dispatcher workers, verify delivery latency, and notify #realtime-ops.",
                difficulty="medium",
                required_slots=["scaling_execution", "restart_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-tr-14",
                prompt="Canary update 'search-ranking' v4.1.0, verify relevance endpoint health, and notify #search-ops.",
                difficulty="medium",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-tr-15",
                prompt="Peak-hour prep: deploy 'session-router' v5.0.0, scale to 14, verify token refresh stability, and notify #identity-ops.",
                difficulty="medium",
                required_slots=["deployment_execution", "scaling_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
        ]
    },
    {
        "task_id": "medium-incident-response",
        "description": "Goal-driven mitigation of active system anomalies",
        "tasks": [
            Task(
                id="m2-inc-1",
                prompt="502 storm on 'edge-proxy': restart the service tier, deploy emergency routing hotfix, verify recovery, and notify #incident-room.",
                difficulty="medium",
                required_slots=["restart_execution", "deployment_execution", "deployment_verification", "restart_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-2",
                prompt="DB saturation event: restart 'connection-pooler', scale down 'background-jobs', verify pressure drops, and notify #incident-room.",
                difficulty="medium",
                required_slots=["restart_execution", "scaling_execution", "restart_verification", "restart_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-3",
                prompt="'auth-validator' deadlock: scale to 0 then back to 5, verify health, deploy lock-fix patch, and notify #backend-sev.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "deployment_execution", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-4",
                prompt="Corrupted rollout in 'payment-service': rollback immediately, restart dependent queue workers, verify payment flow, and notify #finance-alerts.",
                difficulty="medium",
                required_slots=["rollback_execution", "restart_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-5",
                prompt="Stale config in 'checkout-ui': restart config-agent, deploy corrected bundle, verify freshness, and notify #web-incident.",
                difficulty="medium",
                required_slots=["restart_execution", "deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-6",
                prompt="Latency regression in 'recommendation-engine': deploy performance patch, scale to 12, verify latency, rollback if still degraded, and alert #ml-incident.",
                difficulty="medium",
                required_slots=["deployment_execution", "scaling_execution", "deployment_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="m2-inc-7",
                prompt="Message backlog in 'worker-queue': scale to 20, restart scheduler, verify throughput recovery, and notify #backend.",
                difficulty="medium",
                required_slots=["scaling_execution", "restart_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-8",
                prompt="TLS handshake errors on 'api-gateway': deploy cert bundle, restart gateway, verify handshake success, and notify #security-incident.",
                difficulty="medium",
                required_slots=["deployment_execution", "restart_execution", "restart_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-9",
                prompt="Disk pressure on 'log-aggregator': scale down ingest workers, rollback latest parser update, verify stability, and notify #data-incident.",
                difficulty="medium",
                required_slots=["scaling_execution", "rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-10",
                prompt="Cascading timeouts: restart 'cache-layer', scale 'edge-proxy' to 8, verify end-to-end health, and notify #incident-room.",
                difficulty="medium",
                required_slots=["restart_execution", "scaling_execution", "restart_verification", "restart_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-11",
                prompt="Queue saturation in 'order-router': scale workers to 22, verify queue drain, and notify #backend.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-inc-12",
                prompt="Auth outage mitigation: deploy emergency auth patch, restart 'auth-validator', verify login flow, and notify #incident-room.",
                difficulty="medium",
                required_slots=["deployment_execution", "restart_execution", "restart_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-13",
                prompt="Bad config reached production on 'checkout-api': rollback latest release, verify checkout health, and notify #finance-alerts.",
                difficulty="medium",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-inc-14",
                prompt="Intermittent 503s on 'gateway-api': restart service tier, deploy retry-policy fix, verify endpoint stability, and notify #web-incident.",
                difficulty="medium",
                required_slots=["restart_execution", "deployment_execution", "deployment_verification", "restart_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-inc-15",
                prompt="CPU spike in 'search-indexer': scale to 15, verify indexing throughput, rollback latest optimization if unstable, and notify #search-ops.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=4,
            ),
        ]
    },
    {
        "task_id": "medium-maintenance-operations",
        "description": "Routine and scheduled maintenance operations",
        "tasks": [
            Task(
                id="m2-maint-1",
                prompt="Quarterly cert rotation: deploy new cert bundle to 'ingress-gateway', restart it, verify trust chain, and notify #security.",
                difficulty="medium",
                required_slots=["deployment_execution", "restart_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-maint-2",
                prompt="Off-peak cleanup: rollback temporary feature in 'internal-admin-tool', scale background workers to 4, verify health, and notify #ops-chat.",
                difficulty="medium",
                required_slots=["rollback_execution", "scaling_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-maint-3",
                prompt="Dependency refresh: deploy patched 'log-aggregator', verify ingestion integrity, and notify #security.",
                difficulty="medium",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-maint-4",
                prompt="Capacity rebalance: scale 'report-generator' down to 3 and 'metrics-exporter' up to 7, verify both paths, and notify #infra.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-maint-5",
                prompt="Scheduled bounce: restart 'sso-router', verify session continuity, and notify #ops-readiness.",
                difficulty="medium",
                required_slots=["restart_execution", "restart_verification", "restart_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-maint-6",
                prompt="Audit hardening: rollback legacy permission profile, deploy audited config, verify access paths, and notify #compliance.",
                difficulty="medium",
                required_slots=["rollback_execution", "deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-maint-7",
                prompt="Storage optimization: scale 'log-aggregator' to 5, restart shipper agents, verify pipeline lag, and notify #data-ops.",
                difficulty="medium",
                required_slots=["scaling_execution", "restart_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-maint-8",
                prompt="Compliance drill: deploy monitoring agent v2.3 to 'audit-logger', restart service, verify signal quality, and notify #security.",
                difficulty="medium",
                required_slots=["deployment_execution", "restart_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-maint-9",
                prompt="Maintenance window: patch 'vpn-gateway', verify tunnel health, then scale to 6 and notify #network.",
                difficulty="medium",
                required_slots=["deployment_execution", "deployment_verification", "scaling_execution", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-maint-10",
                prompt="Cost-control rollback: revert experimental collector on 'metrics-exporter', verify dashboards, and notify #finance-alerts.",
                difficulty="medium",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-maint-11",
                prompt="Monthly patch cycle: deploy 'api-gateway' maintenance patch, verify health checks, and notify #platform-ops.",
                difficulty="medium",
                required_slots=["deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-maint-12",
                prompt="Maintenance rebalance: scale 'log-aggregator' to 6, verify ingestion lag, and notify #data-ops.",
                difficulty="medium",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-maint-13",
                prompt="Scheduled cert renewal: deploy updated cert chain, restart 'vpn-gateway', verify tunnel health, and notify #network.",
                difficulty="medium",
                required_slots=["deployment_execution", "restart_execution", "restart_verification", "deployment_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="m2-maint-14",
                prompt="Audit sweep: rollback temporary debug policy, verify audit trail integrity, and notify #compliance.",
                difficulty="medium",
                required_slots=["rollback_execution", "rollback_verification", "rollback_notification"],
                baseline_call_count=3,
            ),
            Task(
                id="m2-maint-15",
                prompt="Stability maintenance: restart 'metrics-exporter', scale 'report-generator' to 5, verify dashboards, and notify #infra.",
                difficulty="medium",
                required_slots=["restart_execution", "scaling_execution", "restart_verification", "restart_notification"],
                baseline_call_count=4,
            ),
        ]
    },
    {
        "task_id": "hard-project-legacy-migration",
        "description": "Project: Decommissioning Legacy Data Center to Cloud",
        "tasks": [
            Task(
                id="h2-mig-1",
                prompt="Phase 1 bridge-up: deploy 'cloud-connector-v2', scale to 30 replicas, verify cross-region sync, and notify #migration-hq.",
                difficulty="hard",
                required_slots=["deployment_execution", "scaling_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-mig-2",
                prompt="Phase 2 mirror: deploy replication policy update, restart 'global-load-balancer', verify mirrored traffic, and notify #migration-war-room.",
                difficulty="hard",
                required_slots=["deployment_execution", "restart_execution", "restart_verification", "deployment_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-mig-3",
                prompt="Phase 3 partial cutover: scale legacy capacity down by 40%, scale cloud-services up, verify regional stability, and notify #migration-war-room.",
                difficulty="hard",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
            Task(
                id="h2-mig-4",
                prompt="Phase 4 failure drill: deploy 'chaos-probe', verify blast-radius controls, rollback probe if error budget is breached, and notify #incident-response.",
                difficulty="hard",
                required_slots=["deployment_execution", "deployment_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-mig-5",
                prompt="Phase 5 schema wave: deploy 'schema-translator', restart 'auth-validator', verify token issuance, rollback translator on auth failures, and notify #migration-hq.",
                difficulty="hard",
                required_slots=["deployment_execution", "restart_execution", "deployment_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=6,
            ),
            Task(
                id="h2-mig-6",
                prompt="Phase 6 final shift: scale legacy to 5%, deploy 'final-proxy-config', verify end-to-end traffic, and notify #migration-complete.",
                difficulty="hard",
                required_slots=["scaling_execution", "deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-mig-7",
                prompt="Phase 7 decommission rehearsal: restart 'audit-logger', scale 'legacy-monolith' to 0, verify audit continuity, and notify #ciso-updates.",
                difficulty="hard",
                required_slots=["restart_execution", "scaling_execution", "restart_verification", "restart_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-mig-8",
                prompt="Phase 8 rollback contingency: deploy backup-route policy, verify cloud path health, scale legacy back to 20 if unstable, and notify #incident-response.",
                difficulty="hard",
                required_slots=["deployment_execution", "deployment_verification", "scaling_execution", "deployment_notification"],
                baseline_call_count=5,
            ),
        ]
    },
    {
        "task_id": "hard-project-zero-trust",
        "description": "Project: Zero-Trust Security Mesh Implementation",
        "tasks": [
            Task(
                id="h2-sec-1",
                prompt="Phase 1 bootstrap: deploy sidecar injector, restart namespace manager to apply webhooks, verify mTLS handshake, and notify #security-ops.",
                difficulty="hard",
                required_slots=["deployment_execution", "restart_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-sec-2",
                prompt="Phase 2 cert surge prep: scale certificate-authority to 14, deploy rotation policy, verify issuance latency, and notify #security-ops.",
                difficulty="hard",
                required_slots=["scaling_execution", "deployment_execution", "deployment_verification", "scaling_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-sec-3",
                prompt="Phase 3 strict enforcement: deploy 'strict-mtls-policy-v3', verify billing and checkout paths, rollback on any critical failure, and page #sec-incidents.",
                difficulty="hard",
                required_slots=["deployment_execution", "deployment_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-sec-4",
                prompt="Phase 4 perimeter reduction: scale 'legacy-vpn-gateway' to 1, deploy deny-list ingress rules, verify external connectivity contracts, and notify #network.",
                difficulty="hard",
                required_slots=["scaling_execution", "deployment_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-sec-5",
                prompt="Phase 5 workload cert refresh: deploy cert bundle to billing stack, restart billing pods, verify cert propagation, and notify #security-ops.",
                difficulty="hard",
                required_slots=["deployment_execution", "restart_execution", "restart_verification", "deployment_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-sec-6",
                prompt="Phase 6 audit hardening: deploy 'audit-sink-v2', scale audit-logger to 12, verify retention signals, and notify #ciso-updates.",
                difficulty="hard",
                required_slots=["deployment_execution", "scaling_execution", "deployment_verification", "deployment_notification"],
                baseline_call_count=5,
            ),
            Task(
                id="h2-sec-7",
                prompt="Phase 7 breach drill: deploy emergency isolation policy, restart ingress-controller, verify traffic segmentation, rollback on control-plane errors, and notify #security-war-room.",
                difficulty="hard",
                required_slots=["deployment_execution", "restart_execution", "restart_verification", "rollback_execution", "rollback_notification"],
                baseline_call_count=6,
            ),
            Task(
                id="h2-sec-8",
                prompt="Phase 8 completion: scale certificate-authority to steady-state 6, verify cluster-wide mTLS health, and notify #security-ops.",
                difficulty="hard",
                required_slots=["scaling_execution", "scaling_verification", "scaling_notification"],
                baseline_call_count=4,
            ),
        ]
    },
]

